name: Test tools

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    if: ${{ github.repository == 'pytorch/pytorch' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6 - 3.9'
          architecture: x64
      - name: Checkout PyTorch
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          fetch-depth: 0 # deep clone, to allow us to use git log
      - name: Install dependencies
        # mypy and boto3 versions copied from
        # .circleci/docker/common/install_conda.sh
        run: |
          set -eux
          pip install -r requirements.txt
          pip install boto3==1.16.34
          make setup_lint
      - name: Test tools
        run: python -m unittest discover -vs tools/test -p 'test_*.py'

concurrency:
  group: test-tools-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
