  # the following clones pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7's tests but enables
  # slow tests and sets an environment variable so gradcheck runs with fast_mode=False
  slow-gradcheck-scheduled-ci:
    triggers:
      - schedule:
          # runs every 8 hours on the 45th minute
          cron: "45 0,8,16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker_build_job:
          name: "docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
          image_name: "pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
      - pytorch_linux_build:
          name: periodic_pytorch_xenial_cuda10_2_cudnn7_gcc7_build
          requires:
            - "docker-pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
          build_environment: "pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7-build"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
      - pytorch_linux_test:
          name: periodic_pytorch_xenial_cuda10_2_cudnn7_gcc7_old_gradcheck_test1
          requires:
            - periodic_pytorch_xenial_cuda10_2_cudnn7_gcc7_build
          build_environment: "pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7-old-gradcheck-test1"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
          use_cuda_docker_runtime: "1"
          resource_class: gpu.medium
      - pytorch_linux_test:
          name: periodic_pytorch_xenial_cuda10_2_cudnn7_gcc7_old_gradcheck_test2
          requires:
            - periodic_pytorch_xenial_cuda10_2_cudnn7_gcc7_build
          build_environment: "pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7-old-gradcheck-test2"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7"
          use_cuda_docker_runtime: "1"
          resource_class: gpu.medium
